### ISSUE TITLE
Check for changes in Module

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-helloworld-module#7]
The `Module` class had or probably will have the following argument `EventEmitter emitter`. However this is not the case at the moment. This leads to build errors. These have been "fixed" in #6 but maybe @jasinai and I missed something because we don't know why `Module` currently does not have this argument or why it would needs this.

Please have a look into this.

**Comment by L-Henke** [comment]
I guess a module can either use its own event emitter, or just use the default event emitter, if every listener should get the event.

**Comment by L-Henke** [comment]
The constructor with ```EventEmitter emitter``` will be required after https://github.com/Qabel/qabel-core/issues/338. I'll redo this and include a valid test after https://github.com/Qabel/qabel-core/issues/338 has been done.
